[package]
name = "easygit"
authors = ["Jabed Zaman < [email protected] >"]
description = "A command line tool to help you with git commands"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
